clear all

clc

%% define the plot value
width = 15;
height = 7;
x0 = 10;
y0 = 10;

figure('Units','centimeters',...
    'Position',[x0 y0 width height],...
    'PaperPositionMode','auto');
hold on
%% plot scatter plots
Index = load('kmean_index.txt');
oldfolder = cd('../data');
X = load('No_plateau_initial_sut.txt');
X(16,:)=[];
cd(oldfolder)
subplot(121)
h1_Xplot = plot(X(~any(Index - 2,1),3),X(~any(Index - 2,1),2));
hold on
h2_Xplot = plot(X(~any(Index - 1,1),3),X(~any(Index - 1,1),2));
hold on

set(gca,...
    'Units','normalized',...
    'Position',[.15 .25 .32 .55],...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',8,...
    'FontName','Times New Roman',...
    'box','on');

set(h1_Xplot,...
    'linestyle','none',...
    'LineWidth',1,...
    'Marker','o',...
    'MarkerEdgeColor','k',...
    'MarkerSize',5);

set(h2_Xplot,...
    'linestyle','none',...
    'LineWidth',1,...
    'Marker','x',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','k',...
    'MarkerSize',9);
xlim([0 50])


hxlabel = xlabel('Initial performance level');
hylabel = ylabel({'Final performance', 'level'});
set([hxlabel,hylabel]           ,...
    'FontUnits'     ,'points'           ,...
    'FontWeight'    ,'normal'           ,...
    'FontName'      ,'Times New Roman'  ,...
    'FontSize'      ,9                 );

subplot(122)
h1_Xplot = plot(X(~any(Index - 2,1),3),X(~any(Index - 2,1),1));
hold on
h2_Xplot = plot(X(~any(Index - 1,1),3),X(~any(Index - 1,1),1));
hold on


set(gca,...
    'Units','normalized',...
    'Position',[.65 .25 .32 .55],...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',8,...
    'FontName','Times New Roman',...
    'box','on');
set(h1_Xplot,...
    'linestyle','none',...
    'LineWidth',1,...
    'Marker','o',...
    'MarkerEdgeColor','k',...
    'MarkerSize',5);

set(h2_Xplot,...
    'linestyle','none',...
    'LineWidth',1,...
    'Marker','x',...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','k',...
    'MarkerSize',9);



hxlabel = xlabel({'Initial performance level'});
hylabel = ylabel({'Number of trials ';'to reach proficiency'});
set([hxlabel,hylabel]           ,...
    'FontUnits'     ,'points'           ,...
    'FontWeight'    ,'normal'           ,...
    'FontName'      ,'Times New Roman'  ,...
    'FontSize'      ,9                 );

figure
T = load('T.txt');
for i = 1:13
    if Index(i) == 1
        type = 'x';
    else
        type = 'o';
    end
    plot(T(i),0,type);
    hold on
end