clear all
close all
clc

oldfolder = cd('../data');
load('data50.txt')
X = data50;
clear data50
cd(oldfolder)
width = 18.7;
height = 14.7;
x0 = 10;
y0 = 1;
load('c.mat')
figure('Units','centimeters',...
    'Position',[x0 y0 width height],...
    'PaperPositionMode','auto');
hold on
X(21,7) = NaN;
Study1_idx = [1 2 3 4];
Study3_idx = [5 6 7 8 9 10];
Study4_idx = [11 12];
Study5_idx = [13 14 15 16 17];


subplot(411)
markers = '+o*xsd';
for i = 1:4
    plot(1:50,X(1:50,Study1_idx(i)),...
        'marker',markers(i),...
        'markeredgecolor','k',...
        'LineStyle','-',...
        'Color','k')
    hold on
end
axis([0 50 0 120])
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'YTick',0:50:100,...
    'FontWeight','normal',...
    'FontSize',8,...
    'FontName','Times New Roman',...
    'box','off');
hXLabel = xlabel('Trial number');
hYLabel = ylabel({'Proficiency level';'(FLS score)'});
set([hXLabel, hYLabel]                  ,...
    'FontUnits'     ,'points'           ,...
    'FontWeight'    ,'normal'           ,...
    'FontName'      ,'Times New Roman'  ,...
    'FontSize'      ,8                 );
legend('Subject 1','Subject 2','Subject 3','Subject 4',...
    'location','northeastoutside');


subplot(412)
for i = 1:6
    plot(1:50,X(1:50,Study3_idx(i)),...
        'marker',markers(i),...
        'markeredgecolor','k',...
        'LineStyle','-',...
        'Color','k')
    hold on
end
axis([0 50 0 120])
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'YTick',0:50:100,...
    'FontWeight','normal',...
    'FontSize',8,...
    'FontName','Times New Roman',...
    'box','off');
hXLabel = xlabel('Trial number');
hYLabel = ylabel({'Proficiency level';'(FLS score)'});
set([hXLabel, hYLabel]                  ,...
    'FontUnits'     ,'points'           ,...
    'FontWeight'    ,'normal'           ,...
    'FontName'      ,'Times New Roman'  ,...
    'FontSize'      ,8                 );
legend('Subject 5','Subject 6','Subject 7',...
    'Subject 8','Subject 9','Subject 10',...
    'location','northeastoutside');

subplot(413)
for i = 1:2
    plot(1:50,X(1:50,Study4_idx(i)),...
        'marker',markers(i),...
        'markeredgecolor','k',...
        'LineStyle','-',...
        'Color','k')
    hold on
end
axis([0 50 0 120])
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'YTick',0:50:100,...
    'FontWeight','normal',...
    'FontSize',8,...
    'FontName','Times New Roman',...
    'box','off');
hXLabel = xlabel('Trial number');
hYLabel = ylabel({'Proficiency level';'(FLS score)'});
set([hXLabel, hYLabel]                  ,...
    'FontUnits'     ,'points'           ,...
    'FontWeight'    ,'normal'           ,...
    'FontName'      ,'Times New Roman'  ,...
    'FontSize'      ,8                 );
legend('Subject 11','Subject 12',...
    'location','northeastoutside');
subplot(414)
for i = 1:5
    plot(1:50,X(1:50,Study5_idx(i)),...
        'marker',markers(i),...
        'markeredgecolor','k',...
        'LineStyle','-',...
        'Color','k')
    hold on
end
axis([0 50 0 120])
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'YTick',0:50:120,...
    'FontWeight','normal',...
    'FontSize',8,...
    'FontName','Times New Roman',...
    'box','off');
hXLabel = xlabel('Trial number');
hYLabel = ylabel({'Proficiency level';'(FLS score)'});
set([hXLabel, hYLabel]                  ,...
    'FontUnits'     ,'points'           ,...
    'FontWeight'    ,'normal'           ,...
    'FontName'      ,'Times New Roman'  ,...
    'FontSize'      ,8                 );
legend('Subject 13','Subject 14','Subject 15','Subject 16','Subject 17',...
    'location','northeastoutside');
%% A B texts
h = axes('Position',[0 0 1 1],'Visible','off');
set(gcf,'CurrentAxes',h)
tA = text(.05,0.95,'(A)');
tB = text(.05,0.65,'(B)');
tC = text(.05,0.34,'(C)');
% tD = text(.05,0.26,'(D)');

set([tA,tB,tC],...
    'FontSize',8,...
    'FontName','Times New Roman');
%%
figure
for i = 1:5
    sub = ['51',num2str(i)];
    subplot(sub)
    plot(X(1:50,Study5_idx(i)))
end